### PR TITLE
Eliminated other erroneous ploidy errors.

### LINKED ISSUE #1043: M2 WDL does not fail if a single command line fails in the Filter task
Need ``set -e`` in the command block.  Otherwise, the Filter task continues even if one of the CLI invocations fails.  This makes workflows really hard to debug.

### LINKED ISSUE #1044: FilterByOrientationBias will fail when it (erroneously) determines that it is running on a non-diploid organism.
This caused a failure in a tumor sample.  In OrientationBiasFilterer.java, remove (or change to a warning) on roughly line 60-62. 

```
         if (genotype.getPloidy() != 2) {
                throw new UserException.BadInput("This tool will not run with non-diploid organisms.  Saw GT: " + genotype.getGenotypeString());
            }
```

### PR DESCRIPTION
**Pull request by LeeTL1220**
- Accidentally missed the same error occurring in other places.  Fixed here.

- Also, fixed WDL.

Closes #1043 
Closes #1044

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java [hunk 1]
```diff
@@ -78,26 +79,23 @@ public static String getGenotypeString(final Genotype g, final String fieldName)
...
     public static boolean isGenotypeInTransition(final Genotype g, final Transition transition) {
         Utils.nonNull(g, "Genotype cannot be null");
         Utils.nonNull(transition, "Artifact mode cannot be null");
 
-        if (g.getAlleles().size() != 2) {
-            throw new UserException.BadInput("Cannot run this method on non-diploid genotypes.");
-        }
-        return g.getAllele(0).getDisplayString().equals(String.valueOf(transition.ref())) &&
-                g.getAllele(1).getDisplayString().equals(String.valueOf(transition.call()));
+        return IntStream.range(1,g.getAlleles().size()).anyMatch(i -> g.getAllele(0).getDisplayString().equals(String.valueOf(transition.ref())) &&
```
Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java]: This should be doable with `Allele::basesMatch` without converting the allele and the transition base to `String`s.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java [hunk 2]
```diff
@@ -107,19 +105,14 @@ public static boolean isGenotypeInTransitionWithComplement(final Genotype g, fin
         Utils.nonNull(g, "Genotype cannot be null");
         Utils.nonNull(transition, "Transition cannot be null");
 
-        if (g.getAlleles().size() != 2) {
-            throw new UserException.BadInput("Cannot run this method on non-diploid genotypes.");
-        }
-        final boolean isInTransition = g.getAllele(0).getDisplayString().equals(String.valueOf(transition.ref())) &&
-                g.getAllele(1).getDisplayString().equals(String.valueOf(transition.call()));
+        final boolean isInTransition = isGenotypeInTransition(g, transition);
```
Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java]: This would look more readable to me as `return isGenotypeInTransition(g, transition) || is GenotypeInTransition(g, transition.complement())`.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java (hunk 1 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java]: Done

File: src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java (hunk 2 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/orientationbiasvariantfilter/OrientationBiasUtils.java]: Done
