### PR TITLE
Fixing tau issue

### LINKED ISSUE #563: ACS conversion is erroneous for tau
The conversion is incorrect

### PR DESCRIPTION
**Pull request by LeeTL1220**
Closes #563

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/exome/acsconversion/ACSModeledSegmentUtils.java [hunk 1]
```diff
@@ -112,7 +112,7 @@ public static ACSModeledSegment convertACNVSegmentToACSSegment(final ACNVModeled
         final int targetCount = genome.getTargets().targetCount(acnvModeledSegment.getInterval());
         final int segLabelCNLOH = 2;
         final int hetCount = genome.getSNPs().targetCount(acnvModeledSegment.getInterval());
-        return new ACSModeledSegment(acnvModeledSegment.getInterval(), ModeledSegment.NO_CALL, targetCount, tau/2.0,
+        return new ACSModeledSegment(acnvModeledSegment.getInterval(), ModeledSegment.NO_CALL, targetCount, ParamUtils.log2(tau/2.0),
```
Comment (samuelklee) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/acsconversion/ACSModeledSegmentUtils.java]: This is somewhat confusing.  I think the local variable should be `segmentMeanInLog2CR = acnvModeledSegment.getSegmentMeanPosteriorSummary().getCenter()` (since this is what the ACSModeledSegment constructor takes), rather than `tau`.  This obviates the need to perform and then immediately undo the transformation locally, which is what you currently do.

**Comment by samuelklee** [comment]
I think some additional documentation in both `ACSModeledSegment` and `ACSModeledSegmentUtils` on the definition of `tau` would prevent future confusion.

**Comment by samuelklee** [comment]
some minor comments, back to you @LeeTL1220

**Comment by samuelklee** [comment]
Oh, also, are we sure that everything is kosher with sigmaTau?

**Comment by LeeTL1220** [comment]
I confirmed a long time ago that sigmaTau is okay.  This was an issue with forgetting to specify the value in log2 space.

**Comment by samuelklee** [comment]
OK, good to squash and merge!

**Comment by LeeTL1220** [comment]
Answered issues.  Back to you @samuelklee
