### PR TITLE
Correcting WGS coverage collection to output the correct format.  The…

### LINKED ISSUE #459: SparkGenomeReadCount tool uses the incorrect column headers
Should be the same as ``CalculateTargetCoverage`` in GATK public.

### LINKED ISSUE #468: PadTargets - blows up on "correct" parameters
tag 39c988c2dc7f669306d246a2191d16af50496640

according to the doc, this commandline is correct:
```
./gatk-launch PadTargets -O a.bed
```

but it blows up right away
```
java.lang.IllegalArgumentException: unexpected null file reference
	at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:535)
	at org.broadinstitute.hellbender.utils.Utils.regularReadableUserFile(Utils.java:612)
	at org.broadinstitute.hellbender.tools.exome.TargetUtils.readTargetFile(TargetUtils.java:28)
	at org.broadinstitute.hellbender.tools.exome.PadTargets.doWork(PadTargets.java:49)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:174)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
	at org.broadinstitute.hellbender.Main.main(Main.java:82)
```

### LINKED ISSUE #469: PadTargets - blows up on IAE rather than UserException
tag 39c988c2dc7f669306d246a2191d16af50496640

```
/gatk-launch PadTargets -O a.bed -T /Users/akiezun/IdeaProjects/gatk-protected//src/test/resources/org/broadinstitute/hellbender/tools/exome/targets.bed --padding -1
```

```
java.lang.IllegalArgumentException: Padding must be >= 0
	at org.broadinstitute.hellbender.utils.param.ParamUtils.isPositiveOrZero(ParamUtils.java:147)
	at org.broadinstitute.hellbender.tools.exome.TargetPadder.padTargetsFromBEDFeatures(TargetPadder.java:28)
	at org.broadinstitute.hellbender.tools.exome.PadTargets.doWork(PadTargets.java:51)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:174)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
	at org.broadinstitute.hellbender.Main.main(Main.java:82)
```

this should stop with a UserException and no stacktrace.

### LINKED ISSUE #470: CLI documentation for spark coverage collection is too sparse.
There is not enough information to use the tool.  The description of binsize needs more expansion as does the tool summary.

### PR DESCRIPTION
**Pull request by LeeTL1220**
…n also updated test.

Adding documentation and fixing required parameter in PadTargets.

Made PadTargets throw a user exception.

Closes #470 
Closes #469 
Closes #468 
Closes #459

### CODE REVIEW

**Comment by LeeTL1220** [comment]
@davidbenjamin I assigned you since I want you to look at the hack-y way I had to solve the column formatting issue.  Suggestions/comments welcome.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/PadTargets.java [hunk 1]
```diff
@@ -46,6 +47,10 @@
     @Override
     protected Object doWork() {
 
+        if (padding < 0) {
```
Comment (davidbenjamin) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/PadTargets.java]: What about `ParamUtils.isPositiveOrZero`?

**Comment by davidbenjamin** [comment]
@LeeTL1220 I suppose you were referring to the new method in `TargetCoverageUtils`.  I feel like I haven't done my duty but after looking over it a few times it doesn't strike me as particularly hacky.  This code passes review as far as I'm concerned.

File: src/main/java/org/broadinstitute/hellbender/tools/exome/PadTargets.java (hunk 1 above)
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/PadTargets.java]: Can't because it will throw the wrong type of exception.  I filed an issue #482
