### PR TITLE
Set segment-mean slice-sampling bounds.

### LINKED ISSUE #438: Crash in AllelicCNV due to infinite segment means
``java.lang.IllegalArgumentException: Segment Mean must be finite.``

Happens when trying to convert ACNV sim final seg files into ACS seg file.  Only happens to some samples.

### PR DESCRIPTION
**Pull request by samuelklee**
Closes #438.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/tools/exome/ACNVCopyRatioModeller.java [hunk 1]
```diff
@@ -126,22 +125,27 @@ public ACNVCopyRatioModeller(final SegmentedModel segmentedModel) {
...
+                            .mapToDouble(coverage -> -normalTerm(coverage, newMean, state.variance()))
                             .sum();
-
+                    //slice sample within range given by minimum and maximum non-outlier coverages
+                    final double minimumCoverageInSegment = Collections.min(nonOutlierCoveragesInSegment);
+                    final double maximumCoverageInSegment = Collections.max(nonOutlierCoveragesInSegment);
                     final SliceSampler sampler =
-                            new SliceSampler(rng, logConditionalPDF, state.getMeanInSegment(segment), meanSliceSamplingWidth);
+                            new SliceSampler(rng, logConditionalPDF, state.getMeanInSegment(segment),
+                                    minimumCoverageInSegment, maximumCoverageInSegment, meanSliceSamplingWidth);
```
Comment (LeeTL1220) [inline src/main/java/org/broadinstitute/hellbender/tools/exome/ACNVCopyRatioModeller.java]: It seems that all you did was take advantage of the min and max values of the SliceSampler.
